version: 2
updates:
  # Backend Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "aterreno"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "backend"
      include: "scope"
    # Group minor and patch updates
    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      testing:
        patterns:
          - "@types/*"
          - "jest"
          - "supertest"
          - "ts-jest"

  # Frontend Node.js dependencies  
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "aterreno"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "frontend"
      include: "scope"
    # Group related updates
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
      testing-library:
        patterns:
          - "@testing-library/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      eslint:
        patterns:
          - "eslint*"

  # Infrastructure Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/infra"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "aterreno"
    labels:
      - "dependencies"
      - "infra"
    commit-message:
      prefix: "infra"
      include: "scope"
    # Group CDK and AWS related updates
    groups:
      aws-cdk:
        patterns:
          - "aws-cdk*"
          - "constructs"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "aterreno"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"