FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

# Install dependencies and ensure Next.js binary is available
RUN npm install

COPY . .

# Build the application for production use
RUN npm run build

EXPOSE 3000

# For Docker Compose use 'start', which requires a build
CMD ["npm", "run", "dev"]
